spring.application.name=inji_usecase
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================================
# = CORS CONFIGURATION
# ===============================================
# Comma-separated list of origins to allow for CORS.
# Example: http://localhost:3000,https://your-prod-domain.com
cors.allowed.origins=http://localhost:3000


# ---- Mail (SMTP production) ----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[email id]
spring.mail.password=[app password]
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# Email templates (editable)
mosip.inji-usecase.templates.email.farmer=Dear Farmer,\n\nThank you for registering with us. Your details have been successfully recorded.\n\nWarm regards,\nThe Farmer Support Team
mosip.inji-usecase.templates.email.truckpass=Hello,\n\nYour truckpass has been created and is ready.\n\nRegards,\nTruckpass Team

