# Company Database Configuration
spring.company-datasource.jdbcUrl=jdbc:postgresql://localhost:5432/truckpass
spring.company-datasource.username=postgres
spring.company-datasource.password=postgres
spring.company-datasource.driver-class-name=org.postgresql.Driver

# Driver Database Configuration
spring.driver-datasource.jdbcUrl=jdbc:postgresql://localhost:5432/truckpass
spring.driver-datasource.username=postgres
spring.driver-datasource.password=postgres
spring.driver-datasource.driver-class-name=org.postgresql.Driver

# Farmer Database Configuration (if you need it)
spring.farmer-datasource.jdbcUrl=jdbc:postgresql://localhost:5432/farmer
spring.farmer-datasource.username=postgres
spring.farmer-datasource.password=postgres
spring.farmer-datasource.driver-class-name=org.postgresql.Driver
