# Database configuration for Farmer
spring.farmer-datasource.jdbc-url=jdbc:postgresql://localhost:5432/postgres
spring.farmer-datasource.username=postgres
spring.farmer-datasource.password=Likisidd@2023
spring.farmer-datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

# Database configuration for TruckPass
spring.truckpass-datasource.jdbc-url=jdbc:postgresql://localhost:5432/postgres
spring.truckpass-datasource.username=postgres
spring.truckpass-datasource.password=Likisidd@2023
spring.truckpass-datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
