apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  database-host: {{ .Values.truckpass_usecase.configmaps.db.database_host | quote }}
  database-name: {{ .Values.truckpass_usecase.configmaps.db.database_name | quote }}
  database-port: {{ .Values.truckpass_usecase.configmaps.db.database_port | quote }}
  database-username: {{ .Values.truckpass_usecase.configmaps.db.database_username | quote }}
