## Additional environment variables to set
## Update the below env variables as per the requirement
extraEnvVars:
  - name: DATABASE_HOST
    valueFrom:
      configMapKeyRef:
        key: database-host
        name: db-config
  - name: DATABASE_PORT
    valueFrom:
      configMapKeyRef:
        key: database-port
        name: db-config
  - name: DATABASE_NAME
    valueFrom:
      configMapKeyRef:
        key: database-name
        name: db-config
  - name: DATABASE_USERNAME
    valueFrom:
      configMapKeyRef:
        key: database-username
        name: db-config
  - name: DB_DBUSER_PASSWORD
    value: "DjNyhW7CAW"    # Provide DB_user password
  - name: KEYCLOAK_INTERNAL_URL
    valueFrom:
      configMapKeyRef:
        key: keycloak-internal-url
        name: keycloak-host
  - name: MOSIP_KEYCLOAK_REALM_ROLES
    valueFrom:
      configMapKeyRef:
        key: mosip-keycloak-realm-roles
        name: mosip-keycloak-realm-roles

inji_usecase:
  configmaps:
    db:
      database_host: api-internal.dev-int-inji.mosip.net
      database_name: mosip_certify   # provide db name
      database_port: "5432"
      database_username: certifyuser # provide username
