## Additional environment variables to set
## Update the below env variables as per the requirement
extraEnvVars:
  - name: KEYCLOAK_URL
    value: https://iam.released.mosip.net/auth/
  - name: KEYCLOAK_REALM
    value: mosip
  - name: KEYCLOAK_CLIENT_ID
    value: truckpass-public
  - name: BASE_URL
    value: https://truckpass.dev-int-inji.mosip.net/v1/admin
  - name: VALID_ADMIN_ROLE
    value: TRUCKPASS_ADMIN
