# Production datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mahi@2904
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration for PRODUCTION
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Keep schema handling enabled
spring.jpa.properties.hibernate.hbm2ddl.create_schemas=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# This will automatically convert camelCase to snake_case
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl